config/routes.rb
Rails.application.routes.draw do

  resources :guarantees do
    collection do
      get 'search'
    end
  end

  devise_for :users, :path_prefix => 'profile', controllers: { registrations: 'users/registrations' }

  resources :users

  root 'guarantees#index'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :guarantees

  has_attached_file :avatar, styles: { medium: "800x800", thumb: "800x800" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    resource.add_role(params[:user][:roles])
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [roles: []])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url, notice: 'Usuario creado correctamente'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_url, notice: 'Usuario actualizado correctamente'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Usuario eliminado completamente'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible =  [:first_name, :last_name, :username,:email, { role_ids: [] }, :about]
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      accessible << [:approved]
      params.require(:user).permit(accessible)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    current_user.first_name + " " + current_user.last_name
  end
end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification
  .card
    %h2.card-header Datos de ingreso
    .card-body
      = f.input :first_name, label: 'Nombre'
      = f.input :last_name, label: 'Apellido'
      = f.input :username, label: 'Nombre de usuario'
      = f.input :email, label: 'Correo electronico'
      = f.input :password, label: 'Contraseña'
      = f.input :password_confirmation, label: 'Confirmar Contraseña'
      = f.input :about, label: 'Observación'

      = f.association :roles, collection: Role.all

      = f.button :submit, class: 'btn btn-primary'

app/views/users/edit.html.haml
- content_for(:page_header) do
  | Editar usuario
= render 'form'

app/views/users/index.html.haml
%h2 Usuarios
%hr
.row
 .col-md-4
  = link_to 'Agregar usuario', new_user_path, class: 'btn btn-primary'

.row
 .col-md-12
  %br
  %table.table-hover.display.table(cellspacing="0" width="100%")
   %thead
    %tr
     %th.text-center Nombre de usuario
     %th.text-center Nombre
     %th.text-center Apellido
     %th.text-center Correo electronico
     %th.text-center Roles
     %th.text-center{colspan: 2} Acciones
   %tbody
    - @users.each do |user|
     %tr
      %td.text-center= user.username
      %td.text-center= user.first_name
      %td.text-center= user.last_name
      %td.text-center= user.email
      %td.text-center= user.roles.first.name
      %td= link_to 'Ver', edit_user_path(user), class: 'btn btn-outline-success btn-sm'
      %td= link_to 'Eliminar', { action: :destroy, id: user.id }, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: '¿Esta seguro?' }

app/views/users/new.html.haml
- content_for(:page_header) do
  | Editar usuario
= render 'form'

app/views/users/show.html.haml
%h2
  Perfil de #{full_name}
.ui.divider
.ui.grid
  .row
    .four.wide.column
      .ui.special.cards
        .card
          .blurring.dimmable.image
            .ui.dimmer
              .content
                .center
                  = link_to 'Editar perfil', edit_user_registration_path, class: 'ui inverted button'
            - if @user.avatar?
              = image_tag @user.avatar.url(:thumb)
          .content
            %a.header
              = full_name
            .meta
              %span.date Se unio el
              = @user.created_at.year
            .description
              %p= @user.about
          .extra.content
            %p
              %i.mail.icon
              = @user.email
            %p
              %i.user.icon
              = @user.roles.first.name
    .twelve.wide.column
      .ui.segment
        %h4.header Ultimos movimientos
        .ui.divider
        %p Ultimas garantias ingresadas
      %table.ui.celled.table
        %thead
          %tr
            %th N° Correlativo
            %th Numero de ingreso
            %th Detalle
            %th Agregado por
            - if can? :update, @guarantee
              %th
        %tbody
          - @guarantees.limit(5).each do |guarantee|
            %tr
              %td= guarantee.correlative
              %td= guarantee.income_number
              %td= capitalize_detail(guarantee.detail)
              %td= guarantee.user.first_name + ' ' + guarantee.user.last_name
              - if can? :update, guarantee
                %td= link_to 'Ver', edit_guarantee_path(guarantee), class: 'ui mini teal button'