config/routes.rb
Rails.application.routes.draw do

  resources :guarantees do
    collection do
      get 'search'
    end
  end

  devise_for :users, :path_prefix => 'profile', controllers: { registrations: 'users/registrations' }

  resources :users

  root 'guarantees#index'
end

app/views/assets/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  - if user_signed_in?
    = link_to 'Boletas de garantías', root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li= link_to 'Inicio', root_path, class: 'nav-link'
        %li= link_to full_name, edit_user_registration_path, class: 'nav-link'
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Opciones
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %a= link_to 'Usuarios', users_path, class: 'dropdown-item'
            %a= link_to 'Exportar a Excel', guarantees_path(format: "xlsx"), class: 'dropdown-item'    
        %li= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: 'nav-link'
  - else
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li= link_to "Iniciar sesión", new_user_session_path, class: 'item'