config/routes.rb
Rails.application.routes.draw do

  resources :guarantees do
    collection do
      get 'search'
    end
  end

  devise_for :users, :path_prefix => 'profile', controllers: { registrations: 'users/registrations' }

  resources :users

  root 'guarantees#index'
end

app/models/guarantee.rb
class Guarantee < ApplicationRecord
  resourcify

  extend Enumerize

  searchkick

  auto_increment :correlative

  belongs_to :user

  enumerize :bank_name, in: [:ESTADO, :SANTANDER, :BBVA, :CORPBANCA, :FALABELLA, :RIPLEY, :CHILE, :BICE, :SCOTIABANK, :CREDITO_E_INVERSIONES,
                            :EDWARDS, :INTERNACIONAL, :ITAU, :SECURITY, :PROAVAL, :HDI, :CONSORCIO, :FIRST_AVAL, :NOTARIA,
                            :MASAVAL, :BCI, :-]

  enumerize :state, in: [:DEVUELTA, :VENCIDA, :VIGENTE, :-]

  enumerize :currency_guarantee, in: [:UF, :CLP, :EUR, :US, :-]

  enumerize :devolution_return, in: [:DESPACHO, :DESPACHO_CORRESPONDENCIA, :RETIRO_PERSONAL, :-]

  serialize :guarantee_type, Array

  enumerize :guarantee_type, in: [:GARANTIA, :VALE_VISTA, :LETRA_CAMBIO, :CERTIFICADO_PRORROGA, :CERTIFICADO_FIANZA, :POLIZA_GARANTIA, :PAGARE, :CERTIFICADO]

end

app/controllers/guarantees_controller.rb
class GuaranteesController < ApplicationController
  before_action :set_guarantee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  skip_load_and_authorize_resource :only => :search

  def search
    if params[:search].present?
      @guarantees = Guarantee.search(params[:search], page: params[:page], per_page: 10)
    else
      @guarantees = Guarantee.all
      @guarantees = Guarantee.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def index
    @guarantees = Guarantee.all
    @guarantees = Guarantee.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
    @excel = Guarantee.all

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def show
  end

  def new
    @guarantee = current_user.guarantees.build
  end

  def edit
    authorize! :update, @guarantee
  end

  def create
    @guarantee = current_user.guarantees.build(guarantee_params)

    respond_to do |format|
      if @guarantee.save
        format.html { redirect_to root_path, notice: 'Garantia correctamente creada.' }
        format.json { render :show, status: :created, location: @guarantee }
      else
        format.html { render :new }
        format.json { render json: @guarantee.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @guarantee.update(guarantee_params)
        format.html { redirect_to root_path, notice: 'Garantia correctamente actualizada.' }
        format.json { render :show, status: :ok, location: @guarantee }
      else
        format.html { render :edit }
        format.json { render json: @guarantee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @guarantee.destroy
    respond_to do |format|
      format.html { redirect_to guarantees_url, notice: 'Garantia correctamente eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    def set_guarantee
      @guarantee = Guarantee.find(params[:id])
    end

    def guarantee_params
      params.require(:guarantee).permit(:correlative, :income_number, :income_date, :income_applicant, :borrower_name, :borrower_id, :bank_name, :guarantee_number,
                                        :value_guarantee, :currency_guarantee, :due_date, :state, :bail, :detail, :bip, :devolution_number, :devolution_date,
                                        :devolution_return, :sectorialist_devolution, :email, :technical_unit, :observation, :guarantee_type)
    end
end

#t.integer "correlative"
#t.string "income_number"
#t.date "income_date"
#t.string "income_applicant"
#t.string "borrower_name"
#t.integer "borrower_id"
#t.string "bank_name"
#t.string "guarantee_number"
#t.integer "value_guarantee"
#t.string "currency_guarantee"
#t.date "due_date"
#t.string "state"
#t.string "bail"
#t.string "detail"
#t.string "bip"
#t.string "devolution_number"
#t.date "devolution_date"
#t.string "devolution_return"
#t.string "sectorialist_devolution"
#t.string "email"
#t.string "technical_unit"
#t.text "observation"
#t.datetime "created_at", null: false
#t.datetime "updated_at", null: false
#t.integer "user_id"
#t.string "guarantee_type"

app/helpers/guarantees_helper.rb
module GuaranteesHelper
  def number_to_currency_clp(value_guarantee)
    number_to_currency(value_guarantee, :unit => "$ ", :separator => ".", :precision => 0)
  end

  def capitalize_name(income_applicant)
    income_applicant.gsub(/[A-Za-z']+/,&:capitalize)
  end

  def capitalize_detail(detail)
    detail.try(:capitalize)
  end

  def due_date_format(due_date)
    due_date.try(:strftime, "%d/%m/%Y")
  end

  def devolution_date_format(devolution_date)
    devolution_date.try(:strftime, "%d/%m/%Y")
  end

  def income_date_format(income_date)
    income_date.try(:strftime, "%d/%m/%Y")
  end
end

app/views/guarantees/_form.html.haml
= simple_form_for(@guarantee) do |f|
  = f.error_notification
  .form-group
    .card
      %h2.card-header Datos de ingreso
      .card-body
        = f.input :guarantee_type, label: 'Tipo garantia', include_blank: false
        = f.input :income_number, label: 'Numero de ingreso'
        = f.input :income_applicant, label: 'Solicitante de ingreso'
        = f.input :income_date, label: 'Fecha de ingreso', as: :string, input_html: { class: 'datepicker' }
    %br
    .card
      %h2.card-header Datos prestador
      .card-body
        = f.input :borrower_name, label: 'Nombre tomador'
        = f.input :borrower_id, as: :string, label: 'ID Tomador'
    %br
    .card
      %h2.card-header Bancos
      .card-body
        = f.input :bank_name, label: 'Nombre banco'
    %br
    .card
      %h2.card-header Detalles de la garantia
      .card-body
        = f.input :guarantee_number, label: 'Numero de garantia'
        = f.input :value_guarantee, label: "Valor garantia", as: :string
        = f.input :currency_guarantee, label: "Moneda garantia"
        - if @guarantee.guarantee_type === 'VALE_VISTA'
          = f.input :due_date, as: :string, label: "Fecha de vencimiento", disabled: true, input_html: { class: 'datepicker' }
        - else
          = f.input :due_date, as: :string, label: "Fecha de vencimiento", input_html: { class: 'datepicker' }
        = f.input :bail, label: "Caución"
        = f.input :detail, label: "Detalle"
        = f.input :bip, label: "Codigo BIP"
        = f.input :email, label: 'Correo electronico'
        = f.input :observation, label: 'Observación', input_html: { rows: '2' }
        - if current_user.has_role? :admin
          = f.button :submit, class: 'btn btn-primary'

app/views/guarantees/_second_form.html.haml
= simple_form_for(@guarantee) do |f|
  = f.error_notification
  .form-group
    .card
      %h2.card-header Datos devolución
      .card-body
        = f.input :state, label: "Estado boleta"
        = f.input :devolution_number, label: "Numero de devolución"
        = f.input :devolution_date, as: :string, label: "Fecha de devolución", input_html: { class: 'datepicker' }
        = f.input :devolution_return, label: "Medio de devolución"
        = f.input :sectorialist_devolution, label: "Sectorialista devolución"
        = f.input :technical_unit, label: "Unidad tecnica"
        = f.input :email, label: 'Correo electronico'
        = f.input :observation, label: 'Observación', input_html: { rows: '2' }
    %br
    .card
      %h2.card-header Datos de ingreso
      .card-body
        = f.input :guarantee_number, label: 'Numero de garantia'
        = f.input :income_number, label: 'Numero de ingreso'
        = f.input :income_applicant, label: 'Solicitante de ingreso'
        = f.input :income_date, label: 'Fecha de ingreso', as: :string, input_html: { class: 'datepicker' }
        = f.input :guarantee_type, label: 'Tipo garantia'
    %br
    .card
      %h2.card-header Datos prestador
      .card-body
        = f.input :borrower_name, label: 'Nombre tomador'
        = f.input :borrower_id, as: :string, label: 'ID Tomador'
    %br
    .card
      %h2.card-header Bancos
      .card-body
        = f.input :bank_name, label: 'Nombre banco'
    %br
    .card
      %h2.card-header Detalles de la garantia
      .card-body
        = f.input :value_guarantee, label: "Valor garantia", as: :string
        = f.input :currency_guarantee, label: "Moneda garantia"
        - if @guarantee.guarantee_type == 'VALE_VISTA'
          = f.input :due_date, as: :string, label: "Fecha de vencimiento", disabled: true, input_html: { class: 'datepicker' }
        - else
          = f.input :due_date, as: :string, label: "Fecha de vencimiento", input_html: { class: 'datepicker' }
        = f.input :bail, label: "Caución"

        = f.input :detail, label: "Detalle"

        = f.input :bip, label: "Codigo BIP"
      .btn.btn-group
        - if current_user.has_role? :admin
          = f.button :submit, class: 'btn btn-info'
          = link_to 'Registrar boleta', guarantee, class: 'btn btn-light'
        = link_to 'Cancelar', root_path, class: 'btn btn-secondary'

app/views/guarantees/edit.html.haml
%h2 Garantia
%hr
%h3
  Informacion correlativo: #{@guarantee.correlative}
= render 'second_form', guarantee: @guarantee

app/views/guarantees/index.html.haml
%br
.row
  .col-md-4
    %h4 Garantías
  .col-md-4
    = form_tag search_guarantees_path, method: :get, class: 'form-inline my-2 my-lg-0', role: 'search' do
      = text_field_tag :search, params[:search], class: 'form-control mr-sm-2'
      = button_tag "Buscar", name: nil, class: 'btn btn-outline-success my-2 my-sm-0'
  .col-md-4
    = link_to 'Agregar boleta', new_guarantee_path, class: 'btn btn-outline-primary btn-block'
%br
%table.table-hover.display.table(cellspacing="0" width="100%")
  %thead
    %tr
      %th.text-center Correlativo
      %th.text-center N° Ingreso
      %th.text-center Fecha de ingreso
      %th.text-center Fecha de vencimiento
      %th.text-center Fecha de devolución
      %th.text-center Detalle
      %th.text-center Analista
      %th.text-center Valor de garantía
      %th.text-center{colspan: 2} Acciones
  %tbody
    - @guarantees.each do |guarantee|
      %tr
        %td.text-center= guarantee.correlative
        %td.text-center= guarantee.income_number
        %td.text-center= income_date_format(guarantee.income_date)
        - if guarantee.due_date?
          %td.text-center= due_date_format(guarantee.due_date)
        - else
          %td.text-center Sin fecha de vencimiento
        - if guarantee.devolution_date?
          %td.text-center= devolution_date_format(guarantee.devolution_date)
        - else
          %td.text-center Sin fecha de devolución
        %td= capitalize_detail(guarantee.detail)
        %td= capitalize_name(guarantee.income_applicant)
        - if guarantee.currency_guarantee == 'UF'
          %td.text-center
            = guarantee.value_guarantee
            = guarantee.currency_guarantee
        - else
          %td.text-center
            = number_to_currency_clp(guarantee.value_guarantee)
            = guarantee.currency_guarantee
        %td= link_to 'Ver', edit_guarantee_path(guarantee), class: 'btn btn-outline-success btn-sm'
        %td= link_to 'Eliminar', { action: :destroy, id: guarantee.id }, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: '¿Esta seguro?' }
%br/
.row
  .col-md-4
  .col-md-4
    = will_paginate @guarantees, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
  .col-md-4

app/views/guarantees/new.html.haml
%h1 Nueva boleta de garantia
%hr
= render 'form', guarantee: @guarantee

app/views/guarantees/search.html.haml
= flash[:alert]
%br
.row
  .col-md-4
    %h4 Garantías
  .col-md-4
    = form_tag search_guarantees_path, method: :get, class: 'form-inline my-2 my-lg-0', role: 'search' do
      = text_field_tag :search, params[:search], class: 'form-control mr-sm-2'
      = button_tag "Buscar", name: nil, class: 'btn btn-outline-success my-2 my-sm-0'
  .col-md-4
    = link_to 'Agregar boleta', new_guarantee_path, class: 'btn btn-outline-primary btn-block'
%br
%table.table-hover.display.table(cellspacing="0" width="100%")
  %thead
    %tr
      %th.text-center Correlativo
      %th.text-center N° Ingreso
      %th.text-center Fecha de ingreso
      %th.text-center Fecha de vencimiento
      %th.text-center Fecha de devolución
      %th.text-center Detalle
      %th.text-center Analista
      %th.text-center Valor de garantía
      %th.text-center{colspan: 2} Acciones
  %tbody
    - @guarantees.each do |guarantee|
      %tr
        %td.text-center= guarantee.correlative
        %td.text-center= guarantee.income_number
        %td.text-center= income_date_format(guarantee.income_date)
        - if guarantee.due_date?
          %td.text-center= due_date_format(guarantee.due_date)
        - else
          %td.text-center Sin fecha de vencimiento
        - if guarantee.devolution_date?
          %td.text-center= devolution_date_format(guarantee.devolution_date)
        - else
          %td.text-center Sin fecha de devolución
        %td= capitalize_detail(guarantee.detail)
        %td= capitalize_name(guarantee.income_applicant)
        - if guarantee.currency_guarantee == 'UF'
          %td.text-center
            = guarantee.value_guarantee
            = guarantee.currency_guarantee
        - else
          %td.text-center
            = number_to_currency_clp(guarantee.value_guarantee)
            = guarantee.currency_guarantee
        %td= link_to 'Ver', edit_guarantee_path(guarantee), class: 'btn btn-outline-success btn-sm'
        %td= link_to 'Eliminar', { action: :destroy, id: guarantee.id }, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: '¿Esta seguro?' }
%br/
.row
  .col-md-4
  .col-md-4
    = will_paginate @guarantees, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
  .col-md-4

app/views/guarantees/show.html.erb
<style type="text/css">
  @media print {
    nav {
      display: none;
    }
    body {
      background-color:#FFFFFF;
      background-image:none;
      color:#000000;
    }
    #ad {
      display:none;
    }
    #leftbar {
      display:none;
    }
    #contentarea {
      padding-top: 70px;
      width:100%;
      padding-left: 100px;
    }
    .btn {
      display: none;
    }

  }
</style>
<div id="contentarea">
  <div style="width: 216mm; height: 279mm;">
    <div style="border: 0px solid black;  margin-right: 3px; margin-left: 3px;">
      <h1 style="text-align: center;">REGISTRO DE GARANTIA N°: <%= @guarantee.correlative %> </h1>
      <br>
      <table border="0" cellpadding="1" cellspacing="1">
        <tbody>
          <tr>
            <td style="width: 150px;"><span style="font-weight: bold;">CONTRATISTA</span></td>
            <td style="border-bottom-width: 1px; width: 600px;"><%= @guarantee.borrower_name %></td>
          </tr>
          <tr>
            <td><span style="font-weight: bold;">PROYECTO</span></td>
            <td style="border-bottom-width: 1px; width: 600px"><%= @guarantee.detail %></td>
          </tr>
          <tr>
            <td><span style="font-weight: bold;">SECTORIALISTA</span></td>
            <td style="border-bottom-width: 1px;"><%= @guarantee.income_applicant %></td>
          </tr>
        </tbody>
      </table>
      <br>
      <br>
      <br>
      <table style="text-align: left;" border="0" cellpadding="1" cellspacing="1">
        <tbody>
          <tr>
            <td style="width: 250px;" </td>
            <td style="font-weight: bold; text-align: left;" colspan="2" ><span style="text-decoration: underline;">BOLETA DEVUELTA</span></td>
          </tr>
          <tr>
            <td></td>
            <td style="font-weight: bold; width: 126px;" >BOLETA N&deg;</td>
            <td style="border-bottom-width: 1px; width: 366px;" ><%= @guarantee.guarantee_number %></td>
          </tr>
          <tr>
            <td></td>
            <td style="font-weight: bold; width: 126px;">BANCO</td>
            <td style="border-bottom-width: 1px; width: 366px;"><%= @guarantee.bank_name %></td>
          </tr>
          <tr>
            <td></td>
            <td style="font-weight: bold; width: 126px;">MONTO $</td>
            <td style="border-bottom-width: 1px; width: 366px;"><%= @guarantee.value_guarantee %> <%= @guarantee.currency_guarantee %></td>
          </tr>
          <tr>
            <td></td>
            <td style="font-weight: bold; width: 126px;"><br><br><br>V&deg;B&deg;</td>
            <td style="border-bottom-width: 1px; width: 366px;"></td>
          </tr>
        </tbody>
      </table>
      <br>
      <br>
      <table style="text-align: left; " border="0" cellpadding="2" cellspacing="2">
    <tbody>
      <tr style="font-weight: bold; text-decoration: underline;">
        <td colspan="4">INGRESO GARANTIA A TESORERIA</td>
      </tr>
      <tr>
        <td>DOCUMENTO N&deg;:</td>
        <td style="border-bottom-width: 1px; width: 230px;"><%= @guarantee.income_number %></td>
        <td>FECHA:</td>
        <td style="border-bottom-width: 1px; width: 230px;"><%= @guarantee.income_date %></td>
      </tr>
    </tbody>
  </table>
  <br>
  <br>
  <% if @guarantee.guarantee_type != 'VALE_VISTA' %>
    <table style="text-align: left;" border="0" cellpadding="2" cellspacing="2">
      <tbody>
        <tr style="font-weight: bold; text-decoration: underline;">
          <td colspan="4">DEVOLUCION DE GARANTIA</td>
        </tr>
        <tr>
          <td>DOCUMENTO N&deg;:</td>
          <td style="border-bottom-width: 1px; width: 230px;"><%= @guarantee.devolution_return %></td>
          <td>FFECHA:</td>
          <% if @guarantee.devolution_date? %>
            <td style="border-bottom-width: 1px; width: 230px;"><%= @guarantee.devolution_date %></td>
          <% else %>
            <td style="border-bottom-width: 1px; width: 230px;">-</td>
          <% end %>
        </tr>
        <tr>
          <td>SOLICITADOR POR:</td>
          <td style="border-bottom-width: 1px; width: 230px;" colspan="3"><%= @guarantee.sectorialist_devolution %></td>
        </tr>
        <tr>
          <td>MEDIO DEVOLUCION:</td>
          <td style="border-bottom-width: 1px; width: 230px;" colspan="3"><%= @guarantee.devolution_return %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
  <br>
  <br>
  <a class="btn btn-primary" href="#" onclick="window.print();return false;">Imprimir</a>
  <%= link_to 'Cancelar', root_path, class: 'btn btn-light' %>
    </div>
  </div>
</div>